### ISSUE TITLE
Request for origin paper

### ISSUE THREAD

**Issue by RRRRRusellllll** [RuizhouLiu/DMutDE#1]
This appears to be a code repository for a knowledge graph distillation model. Could you please provide the original paper so I can study it further? Thank you very much!

**Comment by RuizhouLiu** [comment]
Thanks for your attention! Our paper is under reviewing. Feel free to try the code. We will upload our manuscript

**Comment by RuizhouLiu** [comment]
[DMutDE_v2.pdf](https://github.com/RuizhouLiu/DMutDE/blob/main/DMutDE_v2.pdf) see this file

**Comment by RRRRRusellllll** [comment]
I would like to express my heartfelt gratitude to your research group for making the code available in such a timely manner. I will study your paper diligently and sincerely hope that it will be accepted soon. Wishing you all the best in your future research endeavors and continued success in your scientific pursuits.
